### ISSUE TITLE
[Bug]: Response duplicated

### ISSUE THREAD

**Issue by hunterbmt** [QuivrHQ/quivr#2794]
### What happened?

A bug happened!

after pull the lastest version, brain start to give out duplicate result

<img width="932" alt="IMG_6508" src="https://github.com/QuivrHQ/quivr/assets/2920220/516341f3-3b06-4e5f-a818-90c74506602f">

**Comment by hunterbmt** [comment]
@dosu not helpful at all

**Comment by hunterbmt** [comment]
@AmineDiro any idea on this issue ? I confirm it's not FE issue

**Comment by StanGirard** [comment]
@hunterbmt We haven't changed anything. openai might have push a new update with a bug. I'll look deeper into it :/

**Comment by hunterbmt** [comment]
@StanGirard if it help, I make some debugging myself, for some reason, once a while OpenAI will send back a chunk that make tool_calls in gathered_msg empty, therefore the prev_answer in ultis.py/parse_chunk_response has 0 len => duplicate in our logic (since we depend on prev_answer to indicate what is the new answer chunk)

**Comment by StanGirard** [comment]
@AmineDiro might be a bug

**Comment by StanGirard** [comment]
@hunterbmt would love if you could open a PR

**Comment by zdkderpphb** [comment]
@hunterbmt  This problem has also been bothering me for the last few days. In particular, it lies in get_prev_message_str. If gathered_msg has no answer attribute, prev_answer is overwritten with an empty string. This results in len(prev_answer) 0 and this leads to the entire content being listed in answer_str again instead of just the newly added content. 
I have temporarily solved it with a global variable prev_answer and this should then only be overwritten if get_prev_message_str is not empty.  Quick and dirty :)

prev_answer = ""

def parse_chunk_response(
    gathered_msg: AIMessageChunk,
    raw_chunk: dict[str, Any],
    supports_func_calling: bool,
) -> Tuple[AIMessageChunk, ParsedRAGChunkResponse]:
    global prev_answer
    # Init with sources
    answer_str = ""
    # Get the previously parsed answer
    new_prev_answer = get_prev_message_str(gathered_msg)
    # Check if the new_prev_answer is empty, if so, use the old prev_answer
    if new_prev_answer:
        prev_answer = new_prev_answer

Translated with DeepL.com (free version)

**Comment by AmineDiro** [comment]
Hello @zdkderpphb  thanks for taking the time for digging into the bug !

I fixed this in [a971e90](https://github.com/QuivrHQ/quivr/commit/a971e90f4d7f135852e4ec000b6a7769933e5ebd) :). Everything should run smoothly now !

**Comment by zdkderpphb** [comment]
[like]  Michael Leitgeb reacted to your message:
________________________________
